% Search Image Set for Specific Object Using ROIs
imageFiles = ...
  {'elephant.jpg', 'cameraman.tif', ...
  'peppers.png',  'saturn.png',...
  'pears.png',    'stapleRemover.jpg', ...
  'football.jpg', 'mandi.tif',...
  'kids.tif',     'liftingbody.png', ...
  'office_5.jpg', 'gantrycrane.png',...
  'moon.tif',     'circuit.tif', ...
  'tape.png',     'coins.png'};

imds = imageDatastore(imageFiles);
imageIndex = indexImages(imds);

queryImage = imread('clutteredDesk.jpg');
queryROI = [130 175 330 365];

figure
imshow(queryImage)
rectangle('Position',queryROI,'EdgeColor','yellow');
imageIDs = retrieveImages(queryImage,imageIndex,'ROI',queryROI);

bestMatch = imageIDs(1);

figure
imshow(imageIndex.ImageLocation{bestMatch});